Instaclone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from insta import views as user_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('insta.urls'))
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

insta/urls.py
from django.urls import path, include
from .views import (
    PostListView,
    PostCreateView,
    PostDetailView,
    PostUpdateView,
    PostDeleteView,
)

app_name = "insta"

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('new/', PostCreateView.as_view(), name='post_create'),
    path('<int:id>', PostDetailView.as_view(), name='post_detail'),
    path('<int:id>/update/', PostUpdateView.as_view(), name='post_update'),
    path('<int:id>/delete/', PostDeleteView.as_view(), name='post_delete'),
]

insta/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import datetime
from django.conf import settings
from django.urls import reverse
from PIL import Image

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    image = models.ImageField(blank=True, null=True)
    caption = models.TextField()
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='post_likes')
    created_date = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('insta:post_detail', kwargs={"id":self.id})

    def __str__(self):    
        return self.caption 

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_photo = models.ImageField(default='default_avatar.jpg', upload_to='profile_pics')
    name = models.CharField(max_length=50)
    bio = models.TextField(max_length=250)
    follows = models.ManyToManyField('Profile', related_name='followed_by')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self):
        super().save()

        img = Image.open(self.profile_photo.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.profile_photo.path)

insta/forms.py
from django import forms
from .models import Post
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field
from django.contrib.auth.models import User 
from django.contrib.auth.forms import UserCreationForm 
from .models import Profile

class PostForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('Post', 'Post', css_class='btn-primary'))

    class Meta:
        model = Post
        fields = [
            'image',
            'caption'
        ]

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username','email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_photo', 'name', 'bio']

insta/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.urls import reverse
from .forms import PostForm
from .models import Post
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
    RedirectView,
)
from datetime import datetime
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User 
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm

# Create your views here.
class PostListView(ListView):
    template_name = "insta/post_list.html"
    queryset = Post.objects.all().filter(created_date__lte=timezone.now()).order_by('-created_date')
    context_object_name = 'posts'

class PostCreateView(CreateView):
    template_name = 'insta/post_create.html'
    form_class = PostForm
    queryset = Post.objects.all()
    success_url = '/'

    def form_valid(self, form):
        print(form.cleaned_data)
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostDetailView(DetailView):
    template_name = 'insta/post_detail.html'
    queryset = Post.objects.all().filter(created_date__lte=timezone.now())
    
    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Post, id=id_)

class PostUpdateView(UpdateView):
    template_name = 'insta/post_create.html'
    form_class = PostForm 

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Post, id=id_)

    def form_valid(self, form):
        form.instance.author = self.request.user 
        return super().form_valid(form) 

class PostDeleteView(DeleteView):
    template_name = 'insta/post_delete.html'

    def get_object(self):
        id_=self.kwargs.get("id")
        return get_object_or_404(Post, id=id_)

    def get_success_url(self):
        return reverse('insta:post_list')

def register(request):
    if request.method == 'POST':
        print("This shit is working bro.")
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            print(username,"This shit is working")
            messages.success(request, f'Account created for {username} successfully!')
            return redirect('/')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})

@login_required
def profile(request):
    return render(request, 'users/profile.html')

class Profile(DetailView):
    template_name = 'users/profile.html'
    queryset = User.objects.all()
    success_url = '/'

    def get_object(self):
        id_ = self.kwargs.get("username")
        user = get_object_or_404(User, username=id_)
        return user 
        
    def get_context_data(self, *args, **kwargs):
        context = super(Profile,self).get_context_data(*args, **kwargs)
        user = self.get_object()
        context.update({
            'posts' : user.posts.all().filter(created_date__lte=timezone.now()).order_by('-created_date')
        })
        return context 
    def add_follow(self, request):
        user = self.get_object() 
        user.profile.followed_by.add(request.user.profile) 

def edit_profile(request):
    if request.method == "POST":

        user_form = UserUpdateForm(request.POST,instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()

            messages.success(request, f'Your account has been updated successfully!')
            return redirect('profile')

    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)
    context = {
        'user_form': user_form,
        'profile_form': profile_form,
    }

    return render(request, 'users/edit_profile.html', context)

def saved_posts(request):
    posts = Post.objects.filter(saved=True)
    context = {'saved_posts': posts}
    return render(request, 'insta/saved_posts.html', context) 

insta/templates/insta/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/insta.css' %}">
    <title>Instaclone</title>
</head>
<body>
    <header>
        <div class='navigation'>
            <div class='instalogo'>
                <a href="{% url 'login' %}"><i class="fab fa-instagram"></i> </a>
                <a class="vl"></a>
                <a href='/'>Instagram</a>
            </div>
            <div class='search_bar'>
                <input type='text' placeholder='Search'>
                <a href="search"><i class="fas fa-search"></i></a>
            </div> 
            <div class='contact_icons'>
                <a href="explore"><i class="far fa-compass"></i></a>
                {% if user.is_authenticated %}
                    <a href="#"> <i class="far fa-heart"></i> </a>
                    <a href="{% url 'profile' %}"><i class="far fa-user"></i> </a>
                    <a href="{% url 'insta:post_create' %}"> <i class="fas fa-plus"></i></a>
                    <a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i></a>
                {% endif %}
            </div> 
        </div>
    </header>
    <div class='container content_container'>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

insta/templates/insta/post_create.html
{% extends 'insta/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <div class="panel panel-default" style="width: 500px; margin:0 auto;">
        <div class="panel-body">
            {% crispy form %}
            {% csrf_token %}
        </div>
    </div>

{% endblock %}

insta/templates/insta/post_delete.html
{% extends 'insta/base.html' %}

{% block content %}

<form action="." method="POST">{% csrf_token %}
    <h2>Do you want to delete this post</h2>
    <img class='post_image' src="{{ post.image.url }}" alt="">
    <p>{{ post.caption }}</p>
    <p> <input type='submit' value='Yes'/><a href="/">Cancel</a></p>
</form>

{% endblock %}

insta/templates/insta/post_detail.html
{% extends 'insta/base.html' %}

{% block content %}
<div class="detail_card">
    <div class="detail_image">
        <p>{{post.author}}</p>
        <img src="{{post.image.url}}" height="300" alt="">
        <p>{{post.caption}}</p>
    </div>
    <div class="post_detail_info">
        <div class="card_header">
            <div class="profile_image">
                
            </div>
            <div class="post_info">
                <div class="post_name"><a href="">{{ post.author }}</a></div>
                <div class="post_location">Nairobi</div>
            </div>
            <div class="post_options"><a href=""><i class="fas fa-ellipsis-h"></i></a></div>
        </div>
        <div class="detail_bottom">
            <div class="engagement">
                <a href=""><i class="fas fa-heart"></i></a>
                <a href="{% url 'insta:post_detail' post.id %}"><i class="far fa-comment"></i></a>
                <a href=""><i class="far fa-share-square"></i></a>
                <a href="" class="fa-bookmarks"><i class="far fa-bookmark"></i></a>
            </div>
            <div class="likes">
                <a href="#">{{ post.likes.count }} likes</a>
            </div>
            <div class="time_posted">
                {{post.created_date | timesince}} ago
            </div>
            <div class="new_comment_section">
                <form action="">
                    <textarea name="" id="" class="text_comment_area" placeholder="Add a comment..." cols="30" rows="10"></textarea>
                    
                    <button type="submit">Post</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

insta/templates/insta/post_list.html
{% extends 'insta/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="card">
            <div class="card_header">
                <div class="profile_image">

                </div>
                <div class="post_info">
                    <div class="post_name">{{ post.author }}</div>
                    <div class="post_location">Nairobi</div>
                </div>
                <div class="post_options"><i class="fas fa-ellipsis-h"></i></div>
            </div>
            <div class="post_image">
                {% if post.image %}
                    <img src="{{ post.image.url }}" alt="">
                {% endif %}
            </div>
            <div class="engagement">
                <a href=""><i class="far fa-heart"></i></a>
                <a href=""><i class="far fa-comment"></i></a>
                <a href=""><i class="far fa-share-square"></i></a>
                <a href=""><i class="far fa-bookmark"></i></a>                
            </div>
            <div class="likes">
                <a href="">240</a>
            </div>
            <div class="caption">
                <a href=""><h2>{{ post.author }}</h2> </a>
                <span><p>{{post.caption}}</p></span>
            </div>
            <div class="time_posted">
                {{ post.created_date | timesince }} ago
            </div>
        </div>
    {% endfor %}
{% endblock %}

insta/templates/insta/saved_posts.html
{% extends 'insta/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="profile_page">
        <div class="media">
            <div>
                <img class="rounded-circle account-img" src="{{ user.profile.profile_photo.url }}" alt="">
            </div>
            <div class="media-body">
                <div class="account-heading">
                    <h2 >{{ user.username }}</h2>
                    <button type="button"><a href="{% url 'edit_profile' %}">Edit profile</a></button>
                    <button><i class="fas fa-cog"></i></button>
                </div>
                <div class="profile_media">
                    <span class="post_count"> <span class="number_of_posts">{{ user.posts.count }}</span> posts </span>
                    <a href=""> <span class="number_of_followers" >1908 </span> followers</a>
                    <a href=""> <span class="number_of_follows" >421 </span> follows</a>

                </div>
                <div class="bio_content">
                    <p class="profilename">{{ user.profile.name }}</p>
                    <p class="text-secondary">{{ user.profile.bio|linebreaks }}</p>
                </div>

            </div>
        </div>
        <br>
        <div class="profile_options">
            <button type="button"><i class="far fa-calendar-alt"></i> POSTS</button>
            <a href="{% url 'insta:post_new' %}"><button type="button"><i class="far fa-plus-square"></i> NEW</button></a>
            <button type="button"><i class="far fa-bookmark"></i> SAVED</button>
        </div>
        <div class="profile_posts">
            {% for post in saved_posts %}
            <a href="" class="post_overlay">
                <i class="far fa-heart hide">{{ post.likes.count }}</i>
                <i class="far fa-comment hide"></i>
                <img src="{{ post.image.url }}" alt="">
            </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

insta/templates/users/edit_profile.html
{% extends 'insta/base.html %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Info</legend>
                {{ user_form|crispy }}
                {{ Profile_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
            </div>
        </form>
    </div>
{% endblock %}

insta/templates/users/login.html
{% extends 'insta/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form action="" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Login</button>
                </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need an account? <a class="ml-2" href="{% url 'register' %}">Sign Up</a>
            </small>
        </div>
    </div>   
{% endblock %}

insta/templates/users/logout.html
{% extends 'insta/base.html' %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a class="ml-2" href="{% url 'login' %}">Login again</a>
        </small>
    </div>
{% endblock %}

insta/templates/users/profile.html
{% extends 'insta/base.html' %}
{% block content %}
    <h2>{{ user.username }}</h2>
{% endblock %}

insta/templates/users/register.html
{% extends 'insta/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form action="" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Now</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already have an account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock %}